### ISSUE TITLE
Improve timer

### ISSUE THREAD

**Issue by danielabdi-noaa** [NOAA-PSL/ufs2arco#16]
Timer object start() and stop() both accept a title. It maybe better to reuse the title supplied in start() for end() as well.
In a multi-threaded situation, where data and computation are done on separate threads, the timer prints are mangled and it can be hard to tell which operation took how many seconds.

**Comment by timothyas** [comment]
Hey @danielabdi-noaa - I am just now seeing this issue. Do you think this is closed with #19 and #20 ?

**Comment by danielabdi-noaa** [comment]
Yes, should be closed now.
